### PR TITLE
Move isolation et. al.

### PR DESCRIPTION
**Pull request by martinthomson**
So, as requested, I've moved the whole stream isolation section from gUM to WebRTC.  In addition to that, I've added more text about isolation, in anticipation of an outcome to some of the discussions in D.C.   You might want to hold onto this until we've had that discussion.

I also fixed up [bug 25774](https://www.w3.org/Bugs/Public/show_bug.cgi?id=25774) while at it.

gUM was a mess whitespace-wise, so I cleaned that up first.

### CODE REVIEW

**Comment by martinthomson** [comment]
Looks like I also addressed [bug 25785](https://www.w3.org/Bugs/Public/show_bug.cgi?id=25785) at the same time.

**Comment by martinthomson** [comment]
See also [bug 25802](https://www.w3.org/Bugs/Public/show_bug.cgi?id=25802)

**Comment by fluffy** [comment]
just one things on whitepspace changes - please send them in a differnt pull request if you can as a general rule of thumb

**Comment by fluffy** [comment]
Martin, can you take your three pull requests and make them into just two. One that has the whitespace changes that we can merge in first. Then once that is merged a second one that has all the changes you have for the peerIdentiy. Ping me when that gets done and I will promptly review and merge. Thanks

**Comment by alvestrand** [comment]
Additional comment: We need you to rebase the pull request - it's been a while since they were updated.

**Comment by martinthomson** [comment]
Acknowledged; I have prioritized this behind the work I'm doing on @http2/http2-spec; next week.

**Pull request closed without merging**
